tap "homebrew/bundle"
tap "homebrew/services"
brew "atuin", restart_service: true
brew "chezmoi"
brew "doctl"
brew "gh"
brew "git"
brew "glab"
brew "gnupg"
brew "helix"
brew "nushell"
brew "openssh"
cask "1password"
cask "1password-cli"
