[Personal]
source = imaps://variable2671@imap.mail.me.com:993
outgoing = smtps://variable2671%40icloud.com@smtp.mail.me.com:587
source-cred-cmd = op read "op://Personal/aerc_icloud/credential"
outgoing-cred-cmd = op read "op://Personal/aerc_icloud/credential"
default = INBOX
from = Karl Hans Laurits <variable2671@icloud.com>
cache-headers = true
